name: Hello World test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Hello World
        run: echo " Hello World , Thsi is my first actions runbook"
        shell: bash
  
  good_bye:
    runs-on: ubuntu-latest

    steps:
      - name: exiting github actions
        run: echo "Completed Github actions, exiting "
        shell: bash