name : testing matrix

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:

        strategy:
            matrix: 
                os: [3.9, 3.10, 3.11]
        
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v5
            
            - name: setup python ${{ matrix.os}}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.os}}
                
            - name: verify python version
              run: python --version
              shell: bash